<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/05/18 07:49:53

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=orangehr',
  'username' => 'root',
  'password' => 'password',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
